// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlrVzd42fBRSjcUDmPH56Uu76wRVwLK0',
    appId: '1:628682241827:web:560a3d7e7c538dfdfd7e96',
    messagingSenderId: '628682241827',
    projectId: 'inventory-app-a7670',
    authDomain: 'inventory-app-a7670.firebaseapp.com',
    storageBucket: 'inventory-app-a7670.appspot.com',
    measurementId: 'G-M53Z98BV4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBosn_XXWfshPjUWpDhXjE9_MSwZ3tB4OQ',
    appId: '1:628682241827:android:df5137eb09bb97b0fd7e96',
    messagingSenderId: '628682241827',
    projectId: 'inventory-app-a7670',
    storageBucket: 'inventory-app-a7670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ-gedHbOLivSsCBHvOw1k4Kl_Ggaw9gw',
    appId: '1:628682241827:ios:fe523f2aad3889cafd7e96',
    messagingSenderId: '628682241827',
    projectId: 'inventory-app-a7670',
    storageBucket: 'inventory-app-a7670.appspot.com',
    iosClientId: '628682241827-hebdbcvg2kmacicrd21cd6h1quq0vfts.apps.googleusercontent.com',
    iosBundleId: 'com.nathanielbattad.newInventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ-gedHbOLivSsCBHvOw1k4Kl_Ggaw9gw',
    appId: '1:628682241827:ios:fe523f2aad3889cafd7e96',
    messagingSenderId: '628682241827',
    projectId: 'inventory-app-a7670',
    storageBucket: 'inventory-app-a7670.appspot.com',
    iosClientId: '628682241827-hebdbcvg2kmacicrd21cd6h1quq0vfts.apps.googleusercontent.com',
    iosBundleId: 'com.nathanielbattad.newInventoryApp',
  );
}
